export interface CropConfig {
  key: string;
  name: string;
  emoji: string;
  cycle_days: number;
  max_biomass_g: number;       // max biomass per plant in grams
  growth_rate: number;          // logistic growth rate constant
  optimal_temp_min: number;
  optimal_temp_max: number;
  optimal_light_hours: number;
  optimal_co2_ppm: number;
  water_ph_min: number;
  water_ph_max: number;
  ec_min: number;              // mS/cm
  ec_max: number;              // mS/cm
  water_litres_per_plant_per_day: number;
  price_per_kg: number;         // INR per kg
  description: string;
  difficulty: "Easy" | "Medium" | "Hard";
  category: "Leafy Green" | "Herb" | "Fruit" | "Spice" | "Microgreen" | "Vegetable";
}

export const CROPS: Record<string, CropConfig> = {
  lettuce: {
    key: "lettuce",
    name: "Lettuce",
    emoji: "🥬",
    cycle_days: 35,
    max_biomass_g: 300,
    growth_rate: 0.18,
    optimal_temp_min: 18,
    optimal_temp_max: 24,
    optimal_light_hours: 16,
    optimal_co2_ppm: 1000,
    water_ph_min: 5.5,
    water_ph_max: 6.5,
    ec_min: 0.8,
    ec_max: 1.2,
    water_litres_per_plant_per_day: 0.3,
    price_per_kg: 120,
    description: "Fast-growing leafy green, ideal for aeroponics beginners.",
    difficulty: "Easy",
    category: "Leafy Green",
  },
  strawberry: {
    key: "strawberry",
    name: "Strawberry",
    emoji: "🍓",
    cycle_days: 90,
    max_biomass_g: 250,
    growth_rate: 0.08,
    optimal_temp_min: 15,
    optimal_temp_max: 22,
    optimal_light_hours: 14,
    optimal_co2_ppm: 900,
    water_ph_min: 5.5,
    water_ph_max: 6.2,
    ec_min: 1.0,
    ec_max: 1.5,
    water_litres_per_plant_per_day: 0.5,
    price_per_kg: 400,
    description: "High-value fruit crop with moderate growth cycle.",
    difficulty: "Medium",
    category: "Fruit",
  },
  saffron: {
    key: "saffron",
    name: "Saffron",
    emoji: "🌸",
    cycle_days: 120,
    max_biomass_g: 5,
    growth_rate: 0.06,
    optimal_temp_min: 15,
    optimal_temp_max: 20,
    optimal_light_hours: 12,
    optimal_co2_ppm: 800,
    water_ph_min: 6.0,
    water_ph_max: 7.0,
    ec_min: 0.5,
    ec_max: 1.0,
    water_litres_per_plant_per_day: 0.15,
    price_per_kg: 300000,
    description: "Ultra-premium spice. Low yield but extremely high value.",
    difficulty: "Hard",
    category: "Spice",
  },
  basil: {
    key: "basil",
    name: "Basil",
    emoji: "🌿",
    cycle_days: 28,
    max_biomass_g: 150,
    growth_rate: 0.22,
    optimal_temp_min: 20,
    optimal_temp_max: 28,
    optimal_light_hours: 14,
    optimal_co2_ppm: 1000,
    water_ph_min: 5.5,
    water_ph_max: 6.5,
    ec_min: 1.0,
    ec_max: 1.6,
    water_litres_per_plant_per_day: 0.25,
    price_per_kg: 250,
    description: "Fast herb with high market demand.",
    difficulty: "Easy",
    category: "Herb",
  },
  spinach: {
    key: "spinach",
    name: "Spinach",
    emoji: "🍃",
    cycle_days: 40,
    max_biomass_g: 200,
    growth_rate: 0.15,
    optimal_temp_min: 15,
    optimal_temp_max: 22,
    optimal_light_hours: 14,
    optimal_co2_ppm: 900,
    water_ph_min: 6.0,
    water_ph_max: 7.0,
    ec_min: 1.8,
    ec_max: 2.3,
    water_litres_per_plant_per_day: 0.3,
    price_per_kg: 80,
    description: "Nutritious leafy green, steady demand.",
    difficulty: "Easy",
    category: "Leafy Green",
  },
  tomato: {
    key: "tomato",
    name: "Tomato",
    emoji: "🍅",
    cycle_days: 80,
    max_biomass_g: 600,
    growth_rate: 0.1,
    optimal_temp_min: 21,
    optimal_temp_max: 27,
    optimal_light_hours: 16,
    optimal_co2_ppm: 1000,
    water_ph_min: 5.5,
    water_ph_max: 6.5,
    ec_min: 2.0,
    ec_max: 3.5,
    water_litres_per_plant_per_day: 0.8,
    price_per_kg: 60,
    description: "High-demand staple. Large biomass, needs strong nutrients.",
    difficulty: "Medium",
    category: "Fruit",
  },
  mint: {
    key: "mint",
    name: "Mint",
    emoji: "🌱",
    cycle_days: 30,
    max_biomass_g: 120,
    growth_rate: 0.2,
    optimal_temp_min: 18,
    optimal_temp_max: 25,
    optimal_light_hours: 14,
    optimal_co2_ppm: 900,
    water_ph_min: 5.5,
    water_ph_max: 6.0,
    ec_min: 1.2,
    ec_max: 1.6,
    water_litres_per_plant_per_day: 0.25,
    price_per_kg: 300,
    description: "Aromatic herb, very fast grower. Great for beverages & culinary use.",
    difficulty: "Easy",
    category: "Herb",
  },
  kale: {
    key: "kale",
    name: "Kale",
    emoji: "🥗",
    cycle_days: 50,
    max_biomass_g: 350,
    growth_rate: 0.13,
    optimal_temp_min: 15,
    optimal_temp_max: 22,
    optimal_light_hours: 14,
    optimal_co2_ppm: 900,
    water_ph_min: 5.5,
    water_ph_max: 6.5,
    ec_min: 1.2,
    ec_max: 2.0,
    water_litres_per_plant_per_day: 0.35,
    price_per_kg: 150,
    description: "Superfood leafy green with rising demand in health-conscious markets.",
    difficulty: "Easy",
    category: "Leafy Green",
  },
  microgreens: {
    key: "microgreens",
    name: "Microgreens",
    emoji: "🌾",
    cycle_days: 14,
    max_biomass_g: 30,
    growth_rate: 0.35,
    optimal_temp_min: 20,
    optimal_temp_max: 25,
    optimal_light_hours: 12,
    optimal_co2_ppm: 800,
    water_ph_min: 5.5,
    water_ph_max: 6.5,
    ec_min: 0.5,
    ec_max: 1.0,
    water_litres_per_plant_per_day: 0.1,
    price_per_kg: 800,
    description: "Ultra-fast harvest cycle (14 days). Premium pricing at restaurants & health stores.",
    difficulty: "Easy",
    category: "Microgreen",
  },
  cucumber: {
    key: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    cycle_days: 60,
    max_biomass_g: 500,
    growth_rate: 0.12,
    optimal_temp_min: 22,
    optimal_temp_max: 28,
    optimal_light_hours: 16,
    optimal_co2_ppm: 1000,
    water_ph_min: 5.5,
    water_ph_max: 6.0,
    ec_min: 1.7,
    ec_max: 2.5,
    water_litres_per_plant_per_day: 0.7,
    price_per_kg: 40,
    description: "Popular salad vegetable. High water consumption but large yields.",
    difficulty: "Medium",
    category: "Vegetable",
  },
};

export const getCropKeys = () => Object.keys(CROPS);
export const getCrop = (key: string): CropConfig | undefined => CROPS[key];
