-- Create active_crops table
CREATE TABLE public.active_crops (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    crop_key TEXT NOT NULL,
    start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expected_harvest_date TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'harvested', 'abandoned')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.active_crops ENABLE ROW LEVEL SECURITY;

-- Add RLS policies for active_crops
CREATE POLICY "Users can view their own active crops"
    ON public.active_crops FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own active crops"
    ON public.active_crops FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own active crops"
    ON public.active_crops FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own active crops"
    ON public.active_crops FOR DELETE
    USING (auth.uid() = user_id);

-- Create crop_tasks table (daily tasks generated by AI)
CREATE TABLE public.crop_tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    active_crop_id UUID NOT NULL REFERENCES public.active_crops(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    day_offset INTEGER NOT NULL, -- Day 1, Day 14, etc.
    task_date TIMESTAMPTZ NOT NULL, -- Calculated based on start_date + day_offset
    title TEXT NOT NULL,
    description TEXT,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.crop_tasks ENABLE ROW LEVEL SECURITY;

-- Add RLS policies for crop_tasks
CREATE POLICY "Users can view their own crop tasks"
    ON public.crop_tasks FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own crop tasks"
    ON public.crop_tasks FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own crop tasks"
    ON public.crop_tasks FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own crop tasks"
    ON public.crop_tasks FOR DELETE
    USING (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX idx_active_crops_user_id ON public.active_crops(user_id);
CREATE INDEX idx_crop_tasks_active_crop_id ON public.crop_tasks(active_crop_id);
CREATE INDEX idx_crop_tasks_user_id_date ON public.crop_tasks(user_id, task_date);
